### ISSUE TITLE
No vertical label in Microsoft Edge browser

### ISSUE THREAD

**Issue by vitaliy-patsay** [pupunzi/jquery.mb.extruder#20]
Hi Matteo,

Thanks for the great plugin. Have you already investigated issue related to vertical label visibility in Microsoft Edge browser. It is reproducible on [demo page](http://pupunzi.com/mb.components/mb.extruder/demo/demo.html).

Here is a [screenshot](http://content.screencast.com/users/nucleus555/folders/Jing/media/3892466b-361a-4ef8-9b3e-c24ac817661d/2016-03-24_1748.png).

**Comment by Securum** [comment]
To fix the flip-labels for Edge.
In jquery.mb.flipText.js change end of line 28 from 

else if (-1! = nAgt.indexOf (“Trident”))

to

else if (-1! = nAgt.indexOf (“Trident”) || -1! = nAgt.indexOf (“Edge”))

/Janne

**Comment by vitaliy-patsay** [comment]
Thanks, Janne! It works. I think you should ask Matteo for a pull request

**Comment by pupunzi** [comment]
The plug-in has been updated to version 2.6.0 with the bug fix.
@Securum thank you
